### ISSUE TITLE
Trouble with access to grafana page on Windows 10

### ISSUE THREAD

**Issue by KravchenkoAlex** [serputko/performance-testing-framework#12]
There is a problem with access to grafana's page afrer "docker-compose up -d" command. After all containers are created, and i try to open localhost:8857 i see the error message on the page (see attachment). This issue is resolved for me in next ways:
1. Turn off your firewall 
2. Set fixed DNS server in Docker's settings (screenshot 2)
3. Uncheck vEthernet (DockerNAT) in Firewall properties (screenshot 3)
![screenshot_2](https://user-images.githubusercontent.com/19817080/46066954-558acd00-c17e-11e8-9bc9-b6e529dd78c3.png)
![screenshot_3](https://user-images.githubusercontent.com/19817080/46066955-558acd00-c17e-11e8-9b95-b6f5900f0d2f.png)
![grafana_error](https://user-images.githubusercontent.com/19817080/46066956-558acd00-c17e-11e8-8ed4-e21393647ada.png)

**Comment by serputko** [comment]
Hello @KravchenkoAlex,
Thanks for reporting. 
Could you please paste here connection timeout error message from grafana log (docker logs grafana) so other users could find this issue by error message text

Thanks in advance

**Comment by KravchenkoAlex** [comment]
yes sure @serputko , here is the screenshot of "docker grafana logs" with error 
![grafana_docker_logs](https://user-images.githubusercontent.com/19817080/46069355-12335d00-c184-11e8-9cb3-382d7077fbdd.png)

**Comment by serputko** [comment]
Great, so it is like:
`Failed to send request. error: Get https://grafana.com/api/plugins/repo/briangann-datatable-panel: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

Thanks
