### ISSUE TITLE
Can't start Jenkins at localhost:8181

### ISSUE THREAD

**Issue by vovadakhniy** [serputko/performance-testing-framework#13]
MAC OS High Sierra
Docker Version 2.0.0.2

**Comment by serputko** [comment]
Hi Vova
Seems that you have some other process running on 8181 port
You can stop that process or just change jenkins port from 8181 to some other one in docker-compose.yml file

**Comment by vovadakhniy** [comment]
@serputko 
I changed it, but did not help.
Could you confirm that you can run  Jenkins with default port (8181) on your machine?

**Comment by vovadakhniy** [comment]
![jk](https://user-images.githubusercontent.com/26628852/51850308-281b7f00-232a-11e9-9554-cd4a27bf3829.png)
![jk2](https://user-images.githubusercontent.com/26628852/51850319-2ce03300-232a-11e9-8fb7-3d11906eb3a2.png)

**Comment by vovadakhniy** [comment]
@serputko 
I'm successfully run all services.
But I'm stuck with launching demo jmeter scenario with BackendJob.
Can't successfully build it - runs with failure every time.
"Unable to find image 'jmeter:latest' locally
docker: Error response from daemon: pull access denied for jmeter, repository does not exist or may require 'docker login'."

![rez1](https://user-images.githubusercontent.com/26628852/51866740-6af14d00-2352-11e9-90da-7133303a1be2.png)
![rez2](https://user-images.githubusercontent.com/26628852/51866744-6f1d6a80-2352-11e9-92c1-9e25aa0a074d.png)

**Comment by serputko** [comment]
@vovadakhniy Sorry for long reply. Seems that i has some old images available and it was not failing on my localhost while testing. 
Could you please do:
go to directory with framework
git pull
docker-compose down
docker-compose build --no-cache jenkins
docker-compose up -d

Thanks

**Comment by vovadakhniy** [comment]
@serputko 
When I run docker-compose up -d
I've got an error ''Cannot start service jenkins''
Maybe I need to update some existing library?
![jk3](https://user-images.githubusercontent.com/26628852/52145942-09d7bb00-266b-11e9-8d1b-ddc19f69d768.png)

**Comment by vovadakhniy** [comment]
@serputko 
Now when I run jmeter scenario with BackendJob I got this one:
![6](https://user-images.githubusercontent.com/26628852/52147325-09412380-266f-11e9-8c97-27a3294a2294.png)
And when I run influxdb localhost:8653 - page not found:
![7](https://user-images.githubusercontent.com/26628852/52147381-37befe80-266f-11e9-917d-b0223f8dcf03.png)

**Comment by serputko** [comment]
Influxdb has no web interface to interact, 404 is ok
You get backend job failed as Jmeter is not starting scenario, could you please execute docker image ls -a command and send me results?

**Comment by vovadakhniy** [comment]
@serputko 
What exactly image?

**Comment by serputko** [comment]
Hello
We successfully started framework from scratch with no problems on few machines yesterday.
Let’s try to do again, just rebuild all
docker-compose pull
docker-compose build 
docker-compose down
docker-compose up -d
