### ISSUE TITLE
[sitespeedio.plugin.webpagetest] Incomplete first view data for WPT test 

### ISSUE THREAD

**Issue by KimberlyGT** [serputko/performance-testing-framework#14]
Hi I worked with framework , but sitespeed.io log display severals errors:
ERROR: [sitespeedio.plugin.webpagetest] Incomplete first view data for WPT test 190211_DF_a4fb5ba5f68e46e0527af73862837557, run 1
 ERROR: [root] Metricsfilter: The breakdown is missing from the metrics breakdown.*.requests
 ERROR: [root] Metricsfilter: The breakdown is missing from the metrics breakdown.*.bytes
![image](https://user-images.githubusercontent.com/47438182/52597148-c1ad5b00-2e17-11e9-9f40-b01aa309c6c7.png)

--webpagetest.host https://www.webpagetest.org --webpagetest.key A.c300ec3e3433db4909d7123c054b6b26 --webpagetest.location Dulles:Chrome --webpagetest.connectivity Cable  --webpagetest.runs 3  --webpagetest.includeRepeatView false --webpagetest.private false

**Comment by serputko** [comment]
Hello
Does that fails jenkins job build?

**Comment by KimberlyGT** [comment]
Hi, not the job is succes: 
![image](https://user-images.githubusercontent.com/47438182/52641889-7ccd0700-2e9f-11e9-8a6c-9a7bd042259e.png)

But I can't view on grafana, webpagetest dashboard.
![image](https://user-images.githubusercontent.com/47438182/52642014-c7e71a00-2e9f-11e9-88c7-1a60b906af10.png)

**Comment by serputko** [comment]
@KimberlyGT That errors in log is ok, that is old integration issue of sitespeed and webpagetest. 
So basically you are not getting metrics in webpagetest dashboard, but you should get metrics for example in Page Summary, like this
![image](https://user-images.githubusercontent.com/16308826/52748576-8d8c9280-2fef-11e9-9e68-b9fb407f904c.png)
Could you check on your side?

**Comment by KimberlyGT** [comment]
@serputko Ok yes, in Page Summary i can view the metrics ... thanks... 
connectivity 4g not is supported?
