### ISSUE TITLE
Grafana can not be accessed at localhost:3000

### ISSUE THREAD

**Issue by sampadrout** [serputko/performance-testing-framework#15]
I have cloned the repo and then run the docker-compose up -d. When i am trying to access grafana at localhost:3000, it says localhost refused to connect. But i am able to access localhost:8181 for jenkins and localhost:9000 for portainer. Any help on this?

**Comment by serputko** [comment]
Hi
Do you have any errors while doing docker-compose up -d?

**Comment by sampadrout** [comment]
Yes, i am getting this error Failed to send request. error: Get https://grafana.com/api/plugins/repo/briangann-datatable-panel: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by serputko** [comment]
Seems that grafana container is not able to connect to grafana.com to download plugins.
Do you have same proxies/firewalls in you network?

**Comment by sampadrout** [comment]
I dont have firewall or proxies enabled on my mac. Interestingly when i have tried the same on my CentOS VM, its working like a charm. Please let me know what info you need to fix this issue?

**Comment by serputko** [comment]
Basically that is not an issue on our side.
Try to do next:
Go to Docker settings > network > DNS server . change from automaic to fixed ( default is 8.8.8.8 )

**Comment by sampadrout** [comment]
Thanks @serputko let me try that. I will update the same in this thread

**Comment by sampadrout** [comment]
You are the man! Yes it worked now. Thanks a ton for providing timely support.
