### ISSUE TITLE
A question about customizing dashboard

### ISSUE THREAD

**Issue by djmanju** [serputko/performance-testing-framework#16]
I really like this dashboard, save me a lot of time indeed to build everything.
Question : How and where can I customize the grafana dashboard 'load-test-monitoring'

**Comment by serputko** [comment]
Hey @djmanju 
you could edit each panel or add new ones to dashboard at the same place where you view dashboard. Basic concepts are placed here: http://docs.grafana.org/guides/getting_started/

**Comment by djmanju** [comment]
thanks @serputko For some reason I can't see edit option on each panel! I see only 'View', 'Share' and 'More> Panel Json'. Is there a way I could edit it on the config file in the backend (I couldn't figure out where the dashboard file is)

**Comment by serputko** [comment]
Got it @djmanju 
You need to login first, login button is in the left bottom corner.
![image](https://user-images.githubusercontent.com/16308826/54727613-64789800-4b81-11e9-94fe-01ac5a68e96a.png)
After that you should be able to edit panels

**Comment by djmanju** [comment]
ah Thank you! That worked. Now I'm able to edit/delete!
