### ISSUE TITLE
I have an issue with running scenario. When I want to run a demo scenario the following error is displayed: "No objects of type FILE and matching include pattern .+\.jmx and not matching exclude pattern  found at path /var/lib/jmeter-scenarios/."

### ISSUE THREAD

**Issue by houfman** [serputko/performance-testing-framework#17]
I didn't change a path
![image](https://user-images.githubusercontent.com/49833240/56791428-b7441000-680f-11e9-9d43-084cbb208522.png)

**Comment by serputko** [comment]
Hi @houfman, do you have demo_scenario.jmx ./jmeter/scenarios/ directory? 
Also which OS do you use?

**Comment by houfman** [comment]
@serputko Yes, I have such a directory
Windows 10
![image](https://user-images.githubusercontent.com/49833240/57075210-d569ae80-6cee-11e9-91bf-80717c359b5c.png)

**Comment by serputko** [comment]
Cool, and did you share C:\ D:\ drives with docker? 
https://blogs.msdn.microsoft.com/stevelasker/2016/06/14/configuring-docker-for-windows-volumes/

**Comment by houfman** [comment]
Yes, I shared. 
When I re-installed Docker, then I see a scenario in Jenkins,  but after a while it disappears

**Comment by a-venger** [comment]
@houfman Try to share it again. Even if check mark exist it is sometimes does not show the real state. Docker on Windows still not 100% stable.
It happened for me as well and I was trying to fix that for several hours but after sharing drives again it works for me perfectly.

**Comment by houfman** [comment]
This is fixed. Thank you so much!
