### ISSUE TITLE
Error when running Influxdb container from docker-compose file

### ISSUE THREAD

**Issue by moataznabil** [serputko/performance-testing-framework#2]
I got this error when I run docker-compose up -d , all the containers are running but there is an error with Influxdb .

I also run 
docker-compose up --build to build the images but the same issue

Error: 
Recreating 1ca2f34b1ced_1ca2f34b1ced_1ca2f34b1ced_1ca2f34b1ced_1ca2f34b1ced_1ca2f34b1ced_influxdb ... error

ERROR: for 1ca2f34b1ced_1ca2f34b1ced_1ca2f34b1ced_1ca2f34b1ced_1ca2f34b1ced_1ca2f34b1ced_influxdb  Cannot start service influxdb: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"/entrypoint1.sh\": permission denied": unknown

ERROR: for influxdb  Cannot start service influxdb: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"/entrypoint1.sh\": permission denied": unknown
ERROR: Encountered errors while bringing up the project.

I'm using mac OS with High sierra version and latest docker version

**Comment by serputko** [comment]
Hi @moataznabil, thanks for your question.
Seems that /entrypoint1.sh doesn't have some permissions.
Make next steps:

1. remove ENTRYPOINT ["/entrypoint1.sh"] line from influxdb/Dockerfile
2. go to project root
3. run docker-compose build --no-cache 
4. docker-compose up -d
5. docker exec -ti influxdb bash
6. ls -la /

And see what are the permissions for entrypoint1.sh file

**Comment by moataznabil** [comment]
@serputko still the same issue when I run docker-compose up -d 

ERROR: for 1ca2f34b1ced_1ca2f34b1ced_1ca2f34b1ced_1ca2f34b1ced_1ca2f34b1ced_1ca2f34b1ced_1ca2f34b1ced_1ca2f34b1ced_1ca2f34b1ced_1ca2f34b1ced_1ca2f34b1ced_1ca2f34b1ced_1ca2f34b1ced_1ca2f34b1ced_1ca2f34b1ced_1ca2f34b1ced_influxdb  Cannot start service influxdb: OCI runtRecreating wptserver ... done
Recreating jenkins ... done

ERROR: for influxdb  Cannot start service influxdb: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"/entrypoint1.sh\": permission denied": unknown
ERROR: Encountered errors while bringing up the project.


the influxdb.Dockerfile is: 

FROM influxdb:latest

COPY entrypoint1.sh /entrypoint1.sh

**Comment by serputko** [comment]
@moataznabil hmmm, after you removed line from dockerfile and made docker-compose build entrypoint1.sh should not be executed.
lets try to remove even copying line (COPY entrypoint1.sh /entrypoint1.sh)

**Comment by moataznabil** [comment]
@serputko yeah , I removed also the (COPY entrypoint1.sh /entrypoint1.sh) and still I have the same error

**Comment by serputko** [comment]
@moataznabil Did you do docker-compose build?

**Comment by moataznabil** [comment]
@serputko yes , actually I tried it with windows machine and it's working fine , So I guess there is an issue with macOS

**Comment by serputko** [comment]
Hi @moataznabil
I've pushed changes that should fix MacOS compatibility, could you check that please?

Thanks
