### ISSUE TITLE
Unable to view the 2 default jenkins job.

### ISSUE THREAD

**Issue by ppanickar** [serputko/performance-testing-framework#22]
I tried following the exact steps as documented , but i am unable to view the Default Backend and Frontend job in Jenkins.
I am using Docker desktop for windows .
what would be resolution for this ?
All the help is highly appreciated.

**Comment by a-venger** [comment]
Have you done this? @ppanickar 
https://docs.microsoft.com/ru-ru/archive/blogs/stevelasker/configuring-docker-for-windows-volumes

**Comment by ppanickar** [comment]
Thank you so much, Worked for me.
Also would like to ask, I tried using my customized .jmx script which executes fine with static data and I am able to see proper metrics in grafana, but while I use CSV(CSV data set config)to fetch dynamic data , the jenkins job fails with below Nullpointer exception:

*************
summary =      0 in 00:00:00 = ******/s Avg:     0 Min: 9223372036854775807 Max: -9223372036854775808 Err:     0 (0.00%)
Tidying up ...    @ Tue Jan 28 10:55:42 UTC 2020 (1580208942890)
**Error generating the report: java.lang.NullPointerException**
... end of run
[BackendJob] $ /bin/sh -xe /tmp/jenkins7635377418839584362.sh
+ docker container stop telegraf
**********************

Can you please help me why i am facing issues while reading dynamic data in my jmeter script.
while the same script works with csv while executing through jmeter locally.
All help is highly appreciated.

**Comment by a-venger** [comment]
Did you place your csv in the jmeter/scnearios folder and changed path to relative in your jmx?

**Comment by ppanickar** [comment]
Worked , Thanks a ton
