### ISSUE TITLE
Aggregate Report

### ISSUE THREAD

**Issue by calvernaz** [serputko/performance-testing-framework#24]
As far as I understand the "Aggregate Report" is generated from two queries. 

I saw in one of your videos that the "Error" count column is merged on the same row. In my case the same table show different rows for the error count, they are not being merged.

Further investigation on this, led me to conclude that the column time is affecting the aggregation. The error field as a different timestamp from the other fields (pct95, etc).

How did you workaround this?

**Comment by serputko** [comment]
Hello @calvernaz, you are right, sometimes it looks not so good :)

Try to use 1 query to aggregate data, this should work fine: 

> SELECT sum(*) as "t" FROM (SELECT
sum("count") as NumberOfSamples,
mean(avg) as Average,
last("pct50.0") as median,
last("pct90.0") as pct90,
last("pct95.0") as pct95,
last("pct99.0") as pct99,
min(min) as Min,
max(max) as Max
FROM "$measurement"
WHERE "statut"='all' 
AND $timeFilter
AND transaction !~ /(all|\/)/
AND "application" =~ /$scenario/ GROUP BY "transaction" )
,
(SELECT
sum(count) as "Error Count"
FROM "$measurement"
WHERE $timeFilter
AND "statut"='ko' 
AND "application" =~ /$scenario/  GROUP BY "transaction") GROUP BY "transaction"

It will provide you next structure
![image](https://user-images.githubusercontent.com/16308826/77865248-125b5f80-7236-11ea-8adb-702d14e639dd.png)

**Comment by calvernaz** [comment]
Gotcha! Thanks, the outer select with aggregation does the trick.
