### ISSUE TITLE
ERROR: for influxdb  Cannot start service influxdb: OCI runtime create failed:

### ISSUE THREAD

**Issue by patel-5788** [serputko/performance-testing-framework#3]
I am geting following error while running docker-compose up  
```
ERROR: for influxdb  Cannot start service influxdb: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"/entrypoint1.sh\": permission denied": unknown
ERROR: Encountered errors while bringing up the project.
```
OS: Ubuntu 16.4

Please guide us to resolve this issue

**Comment by patel-5788** [comment]
I have followed all steps suggested on above thread
https://github.com/serputko/performance-testing-framework/issues/2

**Comment by serputko** [comment]
Hi @learnappium, i’m not at my desk currently will check.
Or maybe you could check permissions for influxdb files with  `ls -la <path_to_influxdb_folder>` ?

Thanks, Anton

**Comment by serputko** [comment]
@learnappium pushed fixes, checked on MacOS. 
Please verify that works fine with ubuntu

Thanks, Anton
