### ISSUE TITLE
Not able to Run Backend job, jenkins "Could not open /var/jenkins_home/workspace/BackendJob/"

### ISSUE THREAD

**Issue by pankajgautam4869** [serputko/performance-testing-framework#30]
Hi,

I am unable to run Backend job successfully as it is unable to reach "/var/jenkins_home/workspace/BackendJob/" directory.

log:
Started by user admin
Running as SYSTEM
Building in workspace /var/jenkins_home/workspace/BackendJob
[BackendJob] $ /bin/sh -xe /tmp/jenkins3857704234177597003.sh
+ docker container ls -a
+ grep telegraf
+ awk { print $8 }
+ check_telegraf=ago
+ [ ago != Up ]
+ echo Starting Telegraf container
Starting Telegraf container
+ docker container start telegraf
telegraf
+ + grepdocker container ls -a jmeter

a12e996a33ef   java:8-jdk            "cat"                    31 minutes ago       Exited (0) 31 minutes ago                                                          jmeter
+ docker container stop jmeter
jmeter
+ docker container rm jmeter
jmeter
[BackendJob] $ /bin/sh -xe /tmp/jenkins3033784653980098952.sh
+ pwd
/var/jenkins_home/workspace/BackendJob
+ ls
demo_scenario.jmx
jmeter.log
monitoring.groovy
+ sudo rm -f report.log
+ sudo rm -rf report/
+ sudo cp -r /var/lib/jmeter-scenarios/demo_scenario.jmx /var/lib/jmeter-scenarios/monitoring.groovy /var/jenkins_home/workspace/BackendJob
+ docker run --name jmeter --net=host --rm --volumes-from=jenkins -e SCENARIO=/var/jenkins_home/workspace/BackendJob/ -e WORKSPACE=/var/jenkins_home/workspace/BackendJob -e USERS=10 -e RAMPUP=180 -e DURATION=600 -e BUILD_NUMBER=11 -e BUILD_URL= java:8-jdk
Mar 26, 2021 5:53:39 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
Could not open /var/jenkins_home/workspace/BackendJob/
[BackendJob] $ /bin/sh -xe /tmp/jenkins3622651381213281158.sh
+ docker container stop telegraf
telegraf
Performing Post build task...
Could not match :Build was aborted  : False
Logical operation result is FALSE
Skipping script  : docker container stop jmeter
END OF POST BUILD TASK 	: 0
Finished: SUCCESS

**Comment by DevOpsFlex** [comment]
Hey,

There is an issue with undefined SCENARIO variable. It should be passed to Jenkins job using [filesystem-list-parameter-plugin](https://github.com/serputko/performance-testing-framework/blob/master/jenkins/jobs/BackendJob.xml#L40-L50) but this plugin doesn't work with Jenkins version: 2.162. 

Try to update Jenkins and resolve issues within run.sh script.

**Comment by pankajgautam4869** [comment]
Hi DevOpsFlex,

I have tried using 2.223(which was working fine on Windows as well Ubuntu previously) and the latest image as well but it's not working now.
Which issue do I need to resolve in run.sh, can you please provide the resolutions with run.sh Script.

Thanks

**Comment by intelligentops** [comment]
Hi @pankajgautam4869 

Please, have a look at https://github.com/intelligentops/performance-testing-framework

**Comment by pankajgautam4869** [comment]
> Hi @pankajgautam4869
> 
> Please, have a look at https://github.com/intelligentops/performance-testing-framework

Thanks @intelligentops,

This worked seamlessly.

**Comment by PrashantSingh-Perf** [comment]
Hi @intelligentops , I tried using your repo , still I am facing same issue i.e. Could not open /var/jenkins_home/workspace/BackendJob/
