### ISSUE TITLE
Not able to see job on jenkins

### ISSUE THREAD

**Issue by Deepak1332** [serputko/performance-testing-framework#33]
localhost:8181, after login to jenkins, we not able to see backend and front end jobs.

Also not sure how to find Jenkins home and where its getting create
<img width="401" alt="Screen Shot 2021-10-14 at 4 32 10 PM" src="https://user-images.githubusercontent.com/13160337/137317873-79055d3d-7e52-49ef-922e-a3d82ff07f70.png">
<img width="1013" alt="Screen Shot 2021-10-14 at 4 30 28 PM" src="https://user-images.githubusercontent.com/13160337/137317885-b5806afb-64f8-4759-b2ff-8dfb01c079f0.png">
d.

**Comment by mastafadhil** [comment]
hi @Deepak1332 , could you please help to share what solved the problem? i am encountering the same issue currently, once the containers are up and running, after logged on to jenkins using intial Password, i was not able to see the jobs as mentioned in the README.md
